package soap

type createData struct {
	pKullaniciAdi        string
	pSifre               string
	WsUserName           string
	WsPassword           string
	pMusteriNo           string
	pChIrsaliyeNo        string
	pPrKiymet            string
	pChBarkod            string
	pGonderiHizmetSekli  string
	pTeslimSekli         string
	pFlAlSms             string
	pFlGnSms             string
	pKargoParcaList      string
	pAliciMusteriAdi     string
	pChSiparisNo         string
	pLuOdemeSekli        string
	pFlAdresFarkli       string
	pChIl                string
	pChIlce              string
	pChAdres             string
	pChTelCep            string
	pChEmail             string
	pMalBedeliOdemeSekli string
	pFlKapidaOdeme       string
	pChIcerik            string
	pAliciMusteriMngNo   string
	pAliciMusteriBayiNo  string
	pChSemt              string
	pChMahalle           string
	pChMeydanBulvar      string
	pChCadde             string
	pChSokak             string
	pChFax               string
	pChVergiDairesi      string
	pChVergiNumarasi     string
	pPlatformKisaAdi     string
	pPlatformSatisKodu   string
	pChTelEv             string
	pChTelIs             string
}
